#Parameter Grids
param_grid <- function(...){
  point <- list(...)
  if(is.null(names(point)) == TRUE){
    stop("Please provide a name for each parameters")
  }
  a <- expand.grid(...)%>% tibble()
  return(a)
}
#' Generate parameters and test the function
#' n <- c(50,100,1000)
#' loc <- c(1,2,3)
#' ttn <- c("bus","train")
#'  param_grid("Money"=n,"Location"=loc,"Transportation" = ttn)


#Data Generation
gen_data <- function(param_list){
  idata <- with(param_list,rnorm(N,mean,sd))
  idata
}


#User Defined function
user_func <- (param_list,idata){#function uses the data that generated by gen_data function
  get_res <- sd(idata)
  get_res
}
summarise_func <- function(param_list,get_res){
  summ <- c(sd=sd(get_res),mu=mean(get_res),lx =length(get_res))
  summ
} 
#examples
gen <- function(param_list){#take inputs from parameter grids but not combination
  N <- param_list$sample_size#n
  aks <- param_list$2#same also here
    asd <- param_list$3#same also here
    #Now we(user) should define the data generation method
    n2 <- rnorm(N,mean=aks)
    n3 <- rnorm(N,sd=asd)
    idata <- data.frame(group = c(rep("r1",N),rep("r2",N)),V = c(n2,n3))
    idata
}

user_func <-(param_list,idata){
  ols <- lm(V~group,data=idata)
  glm <- glm(V ~ group, data = idata)
  get_res <- c(ols = ols$coef,gls= glm$coef)
  get_res
}

summarise <- function(param_list,get_res){
  mean <-  mean(get_res)
  min <- min(get_res)
  max <- max(get_res)
  summ <- list(max,min,mean)#or c 
  sum
}

mc_sim <- function(replication = NULL,summarise=summarise,
                   param_grid = param_grid,user_func= user_func,
                   gen_data=gen_data,parallel = TRUE,seed=NULL,
                   type_parallel = NULL,Workers = NULL){
  
}
